"""add phone number

Revision ID: e3d52ebe6106
Revises: 7b10fea3bfde
Create Date: 2022-08-04 20:39:49.106089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d52ebe6106'
down_revision = '7b10fea3bfde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
